### ISSUE TITLE
Paper view: Search buttons overflow right at certain browser window widths.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#98] opened 2022-02-08 18:06 UTC
![image](https://user-images.githubusercontent.com/1148967/153048722-64f6fe69-7bd9-49c5-a9be-2701031c8833.png)

**Comment by sebgntr** [comment] 2022-02-09 11:06
Duplicate of https://github.com/ir-anthology/ir-anthology/issues/19

**Closed by sebgntr** 2022-02-09 11:06 UTC
Labels: bug, webpage
